#############################################################################
# Makefile for building: ParallelCoordinates.app/Contents/MacOS/ParallelCoordinates
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ParallelCoordinates.pro
# Template: app
# Command: /Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/qmake -o Makefile ParallelCoordinates.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I3rdParty/glm -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib
QMAKE         = /Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ParallelCoordinates1.0.0
DISTDIR = /Users/wolfgangmeyerle/Documents/workspace/Parallel-Coordinates-in-QT/.tmp/ParallelCoordinates1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qrangeslider.cpp \
		qrangesliderobserver.cpp \
		parallelcoordinatesworkerobserver.cpp \
		heightmap.cpp qrc_3dvisualization.cpp \
		moc_mainwindow.cpp \
		moc_qrangeslider.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrangeslider.o \
		qrangesliderobserver.o \
		parallelcoordinatesworkerobserver.o \
		heightmap.o \
		qrc_3dvisualization.o \
		moc_mainwindow.o \
		moc_qrangeslider.o
DIST          = 3dVisualization/fragmentShader.glsl \
		3dVisualization/vertexShader.glsl \
		heightmap.jpg \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		ParallelCoordinates.pro mainwindow.h \
		qrangeslider.h \
		parallelcoordinateswidget.h \
		parallelcoordinatesglobals.h \
		view3d.h \
		dataset.h \
		datastore.h \
		qrangesliderobserver.h \
		parallelcoordinatesworker.h \
		parallelcoordinatesworkerobserver.h \
		vmath.h \
		heightmap.h main.cpp \
		mainwindow.cpp \
		qrangeslider.cpp \
		qrangesliderobserver.cpp \
		parallelcoordinatesworkerobserver.cpp \
		heightmap.cpp
QMAKE_TARGET  = ParallelCoordinates
DESTDIR       = 
TARGET        = ParallelCoordinates.app/Contents/MacOS/ParallelCoordinates


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d ParallelCoordinates.app/Contents/MacOS/ || mkdir -p ParallelCoordinates.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ParallelCoordinates.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		ParallelCoordinates.pro \
		3dvisualization.qrc \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ParallelCoordinates.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
ParallelCoordinates.pro:
3dvisualization.qrc:
../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ParallelCoordinates.pro

qmake_all: FORCE

ParallelCoordinates.app/Contents/PkgInfo: 
	@test -d ParallelCoordinates.app/Contents || mkdir -p ParallelCoordinates.app/Contents
	@$(DEL_FILE) ParallelCoordinates.app/Contents/PkgInfo
	@echo "APPL????" > ParallelCoordinates.app/Contents/PkgInfo
ParallelCoordinates.app/Contents/Resources/empty.lproj: 
	@test -d ParallelCoordinates.app/Contents/Resources || mkdir -p ParallelCoordinates.app/Contents/Resources
	@touch ParallelCoordinates.app/Contents/Resources/empty.lproj
	
ParallelCoordinates.app/Contents/Info.plist: 
	@test -d ParallelCoordinates.app/Contents || mkdir -p ParallelCoordinates.app/Contents
	@$(DEL_FILE) ParallelCoordinates.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Own.ParallelCoordinates,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ParallelCoordinates,g" -e "s,@LIBRARY@,ParallelCoordinates,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >ParallelCoordinates.app/Contents/Info.plist

all: Makefile \
		ParallelCoordinates.app/Contents/PkgInfo \
		ParallelCoordinates.app/Contents/Resources/empty.lproj \
		ParallelCoordinates.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents 3dvisualization.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h qrangeslider.h parallelcoordinateswidget.h parallelcoordinatesglobals.h view3d.h dataset.h datastore.h qrangesliderobserver.h parallelcoordinatesworker.h parallelcoordinatesworkerobserver.h vmath.h heightmap.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp qrangeslider.cpp qrangesliderobserver.cpp parallelcoordinatesworkerobserver.cpp heightmap.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ParallelCoordinates.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_3dvisualization.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_3dvisualization.cpp
qrc_3dvisualization.cpp: 3dvisualization.qrc \
		../../../Qt/5.7/clang_64/bin/rcc \
		fragmentShader.glsl \
		vertexShader.glsl \
		heightmap.jpg
	/Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/rcc -name 3dvisualization 3dvisualization.qrc -o qrc_3dvisualization.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qrangeslider.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qrangeslider.cpp
moc_mainwindow.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		parallelcoordinatesglobals.h \
		datastore.h \
		dataset.h \
		datastore.cpp \
		parallelcoordinateswidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		qrangeslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		qrangesliderobserver.h \
		parallelcoordinatesworker.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		parallelcoordinatesworkerobserver.h \
		parallelcoordinatesworker.cpp \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		parallelcoordinateswidget.cpp \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		view3d.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		3rdParty/glm/glm/mat4x4.hpp \
		3rdParty/glm/glm/detail/type_mat4x4.hpp \
		3rdParty/glm/glm/fwd.hpp \
		3rdParty/glm/glm/detail/type_int.hpp \
		3rdParty/glm/glm/detail/setup.hpp \
		3rdParty/glm/glm/simd/platform.h \
		3rdParty/glm/glm/detail/type_float.hpp \
		3rdParty/glm/glm/detail/type_vec.hpp \
		3rdParty/glm/glm/detail/precision.hpp \
		3rdParty/glm/glm/detail/type_mat.hpp \
		3rdParty/glm/glm/detail/type_vec4.hpp \
		3rdParty/glm/glm/detail/_swizzle.hpp \
		3rdParty/glm/glm/detail/_swizzle_func.hpp \
		3rdParty/glm/glm/detail/type_vec4.inl \
		3rdParty/glm/glm/detail/type_vec4_simd.inl \
		3rdParty/glm/glm/detail/type_mat4x4.inl \
		3rdParty/glm/glm/detail/func_matrix.hpp \
		3rdParty/glm/glm/vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.inl \
		3rdParty/glm/glm/vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.inl \
		3rdParty/glm/glm/vec4.hpp \
		3rdParty/glm/glm/mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.inl \
		3rdParty/glm/glm/mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.inl \
		3rdParty/glm/glm/mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.inl \
		3rdParty/glm/glm/mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.inl \
		3rdParty/glm/glm/mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.inl \
		3rdParty/glm/glm/mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.inl \
		3rdParty/glm/glm/mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.inl \
		3rdParty/glm/glm/mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.inl \
		3rdParty/glm/glm/detail/func_matrix.inl \
		3rdParty/glm/glm/geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.inl \
		3rdParty/glm/glm/detail/func_exponential.hpp \
		3rdParty/glm/glm/detail/type_vec1.hpp \
		3rdParty/glm/glm/detail/type_vec1.inl \
		3rdParty/glm/glm/detail/func_exponential.inl \
		3rdParty/glm/glm/detail/func_vector_relational.hpp \
		3rdParty/glm/glm/detail/func_vector_relational.inl \
		3rdParty/glm/glm/detail/func_vector_relational_simd.inl \
		3rdParty/glm/glm/detail/_vectorize.hpp \
		3rdParty/glm/glm/detail/func_exponential_simd.inl \
		3rdParty/glm/glm/simd/exponential.h \
		3rdParty/glm/glm/detail/func_common.hpp \
		3rdParty/glm/glm/detail/_fixes.hpp \
		3rdParty/glm/glm/detail/func_common.inl \
		3rdParty/glm/glm/detail/func_common_simd.inl \
		3rdParty/glm/glm/simd/common.h \
		3rdParty/glm/glm/detail/func_geometric_simd.inl \
		3rdParty/glm/glm/simd/geometric.h \
		3rdParty/glm/glm/detail/func_matrix_simd.inl \
		3rdParty/glm/glm/simd/matrix.h \
		3rdParty/glm/glm/detail/type_mat4x4_simd.inl \
		view3d.cpp \
		vmath.h \
		3rdParty/glm/glm/gtc/matrix_transform.hpp \
		3rdParty/glm/glm/gtc/constants.hpp \
		3rdParty/glm/glm/gtc/constants.inl \
		3rdParty/glm/glm/gtc/matrix_transform.inl \
		3rdParty/glm/glm/trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.inl \
		3rdParty/glm/glm/detail/func_trigonometric_simd.inl \
		3rdParty/glm/glm/matrix.hpp \
		3rdParty/glm/glm/gtc/type_ptr.hpp \
		3rdParty/glm/glm/gtc/quaternion.hpp \
		3rdParty/glm/glm/gtc/quaternion.inl \
		3rdParty/glm/glm/exponential.hpp \
		3rdParty/glm/glm/gtc/quaternion_simd.inl \
		3rdParty/glm/glm/gtc/type_ptr.inl \
		mainwindow.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/wolfgangmeyerle/Documents/workspace/Parallel-Coordinates-in-QT -I/Users/wolfgangmeyerle/Documents/workspace/Parallel-Coordinates-in-QT/3rdParty/glm -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_qrangeslider.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		parallelcoordinatesglobals.h \
		qrangesliderobserver.h \
		qrangeslider.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/wolfgangmeyerle/Documents/workspace/Parallel-Coordinates-in-QT -I/Users/wolfgangmeyerle/Documents/workspace/Parallel-Coordinates-in-QT/3rdParty/glm -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib qrangeslider.h -o moc_qrangeslider.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		parallelcoordinatesglobals.h \
		datastore.h \
		dataset.h \
		datastore.cpp \
		parallelcoordinateswidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		qrangeslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		qrangesliderobserver.h \
		parallelcoordinatesworker.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		parallelcoordinatesworkerobserver.h \
		parallelcoordinatesworker.cpp \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		parallelcoordinateswidget.cpp \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		view3d.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		3rdParty/glm/glm/mat4x4.hpp \
		3rdParty/glm/glm/detail/type_mat4x4.hpp \
		3rdParty/glm/glm/fwd.hpp \
		3rdParty/glm/glm/detail/type_int.hpp \
		3rdParty/glm/glm/detail/setup.hpp \
		3rdParty/glm/glm/simd/platform.h \
		3rdParty/glm/glm/detail/type_float.hpp \
		3rdParty/glm/glm/detail/type_vec.hpp \
		3rdParty/glm/glm/detail/precision.hpp \
		3rdParty/glm/glm/detail/type_mat.hpp \
		3rdParty/glm/glm/detail/type_vec4.hpp \
		3rdParty/glm/glm/detail/_swizzle.hpp \
		3rdParty/glm/glm/detail/_swizzle_func.hpp \
		3rdParty/glm/glm/detail/type_vec4.inl \
		3rdParty/glm/glm/detail/type_vec4_simd.inl \
		3rdParty/glm/glm/detail/type_mat4x4.inl \
		3rdParty/glm/glm/detail/func_matrix.hpp \
		3rdParty/glm/glm/vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.inl \
		3rdParty/glm/glm/vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.inl \
		3rdParty/glm/glm/vec4.hpp \
		3rdParty/glm/glm/mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.inl \
		3rdParty/glm/glm/mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.inl \
		3rdParty/glm/glm/mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.inl \
		3rdParty/glm/glm/mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.inl \
		3rdParty/glm/glm/mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.inl \
		3rdParty/glm/glm/mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.inl \
		3rdParty/glm/glm/mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.inl \
		3rdParty/glm/glm/mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.inl \
		3rdParty/glm/glm/detail/func_matrix.inl \
		3rdParty/glm/glm/geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.inl \
		3rdParty/glm/glm/detail/func_exponential.hpp \
		3rdParty/glm/glm/detail/type_vec1.hpp \
		3rdParty/glm/glm/detail/type_vec1.inl \
		3rdParty/glm/glm/detail/func_exponential.inl \
		3rdParty/glm/glm/detail/func_vector_relational.hpp \
		3rdParty/glm/glm/detail/func_vector_relational.inl \
		3rdParty/glm/glm/detail/func_vector_relational_simd.inl \
		3rdParty/glm/glm/detail/_vectorize.hpp \
		3rdParty/glm/glm/detail/func_exponential_simd.inl \
		3rdParty/glm/glm/simd/exponential.h \
		3rdParty/glm/glm/detail/func_common.hpp \
		3rdParty/glm/glm/detail/_fixes.hpp \
		3rdParty/glm/glm/detail/func_common.inl \
		3rdParty/glm/glm/detail/func_common_simd.inl \
		3rdParty/glm/glm/simd/common.h \
		3rdParty/glm/glm/detail/func_geometric_simd.inl \
		3rdParty/glm/glm/simd/geometric.h \
		3rdParty/glm/glm/detail/func_matrix_simd.inl \
		3rdParty/glm/glm/simd/matrix.h \
		3rdParty/glm/glm/detail/type_mat4x4_simd.inl \
		view3d.cpp \
		vmath.h \
		3rdParty/glm/glm/gtc/matrix_transform.hpp \
		3rdParty/glm/glm/gtc/constants.hpp \
		3rdParty/glm/glm/gtc/constants.inl \
		3rdParty/glm/glm/gtc/matrix_transform.inl \
		3rdParty/glm/glm/trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.inl \
		3rdParty/glm/glm/detail/func_trigonometric_simd.inl \
		3rdParty/glm/glm/matrix.hpp \
		3rdParty/glm/glm/gtc/type_ptr.hpp \
		3rdParty/glm/glm/gtc/quaternion.hpp \
		3rdParty/glm/glm/gtc/quaternion.inl \
		3rdParty/glm/glm/exponential.hpp \
		3rdParty/glm/glm/gtc/quaternion_simd.inl \
		3rdParty/glm/glm/gtc/type_ptr.inl \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		parallelcoordinatesglobals.h \
		datastore.h \
		dataset.h \
		datastore.cpp \
		parallelcoordinateswidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		qrangeslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		qrangesliderobserver.h \
		parallelcoordinatesworker.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		parallelcoordinatesworkerobserver.h \
		parallelcoordinatesworker.cpp \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		parallelcoordinateswidget.cpp \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		view3d.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		3rdParty/glm/glm/mat4x4.hpp \
		3rdParty/glm/glm/detail/type_mat4x4.hpp \
		3rdParty/glm/glm/fwd.hpp \
		3rdParty/glm/glm/detail/type_int.hpp \
		3rdParty/glm/glm/detail/setup.hpp \
		3rdParty/glm/glm/simd/platform.h \
		3rdParty/glm/glm/detail/type_float.hpp \
		3rdParty/glm/glm/detail/type_vec.hpp \
		3rdParty/glm/glm/detail/precision.hpp \
		3rdParty/glm/glm/detail/type_mat.hpp \
		3rdParty/glm/glm/detail/type_vec4.hpp \
		3rdParty/glm/glm/detail/_swizzle.hpp \
		3rdParty/glm/glm/detail/_swizzle_func.hpp \
		3rdParty/glm/glm/detail/type_vec4.inl \
		3rdParty/glm/glm/detail/type_vec4_simd.inl \
		3rdParty/glm/glm/detail/type_mat4x4.inl \
		3rdParty/glm/glm/detail/func_matrix.hpp \
		3rdParty/glm/glm/vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.inl \
		3rdParty/glm/glm/vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.inl \
		3rdParty/glm/glm/vec4.hpp \
		3rdParty/glm/glm/mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.inl \
		3rdParty/glm/glm/mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.inl \
		3rdParty/glm/glm/mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.inl \
		3rdParty/glm/glm/mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.inl \
		3rdParty/glm/glm/mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.inl \
		3rdParty/glm/glm/mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.inl \
		3rdParty/glm/glm/mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.inl \
		3rdParty/glm/glm/mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.inl \
		3rdParty/glm/glm/detail/func_matrix.inl \
		3rdParty/glm/glm/geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.inl \
		3rdParty/glm/glm/detail/func_exponential.hpp \
		3rdParty/glm/glm/detail/type_vec1.hpp \
		3rdParty/glm/glm/detail/type_vec1.inl \
		3rdParty/glm/glm/detail/func_exponential.inl \
		3rdParty/glm/glm/detail/func_vector_relational.hpp \
		3rdParty/glm/glm/detail/func_vector_relational.inl \
		3rdParty/glm/glm/detail/func_vector_relational_simd.inl \
		3rdParty/glm/glm/detail/_vectorize.hpp \
		3rdParty/glm/glm/detail/func_exponential_simd.inl \
		3rdParty/glm/glm/simd/exponential.h \
		3rdParty/glm/glm/detail/func_common.hpp \
		3rdParty/glm/glm/detail/_fixes.hpp \
		3rdParty/glm/glm/detail/func_common.inl \
		3rdParty/glm/glm/detail/func_common_simd.inl \
		3rdParty/glm/glm/simd/common.h \
		3rdParty/glm/glm/detail/func_geometric_simd.inl \
		3rdParty/glm/glm/simd/geometric.h \
		3rdParty/glm/glm/detail/func_matrix_simd.inl \
		3rdParty/glm/glm/simd/matrix.h \
		3rdParty/glm/glm/detail/type_mat4x4_simd.inl \
		view3d.cpp \
		vmath.h \
		3rdParty/glm/glm/gtc/matrix_transform.hpp \
		3rdParty/glm/glm/gtc/constants.hpp \
		3rdParty/glm/glm/gtc/constants.inl \
		3rdParty/glm/glm/gtc/matrix_transform.inl \
		3rdParty/glm/glm/trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.inl \
		3rdParty/glm/glm/detail/func_trigonometric_simd.inl \
		3rdParty/glm/glm/matrix.hpp \
		3rdParty/glm/glm/gtc/type_ptr.hpp \
		3rdParty/glm/glm/gtc/quaternion.hpp \
		3rdParty/glm/glm/gtc/quaternion.inl \
		3rdParty/glm/glm/exponential.hpp \
		3rdParty/glm/glm/gtc/quaternion_simd.inl \
		3rdParty/glm/glm/gtc/type_ptr.inl \
		ui_mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrangeslider.o: qrangeslider.cpp qrangeslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		parallelcoordinatesglobals.h \
		qrangesliderobserver.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrangeslider.o qrangeslider.cpp

qrangesliderobserver.o: qrangesliderobserver.cpp qrangesliderobserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrangesliderobserver.o qrangesliderobserver.cpp

parallelcoordinatesworkerobserver.o: parallelcoordinatesworkerobserver.cpp parallelcoordinatesworkerobserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parallelcoordinatesworkerobserver.o parallelcoordinatesworkerobserver.cpp

heightmap.o: heightmap.cpp heightmap.h \
		3rdParty/glm/glm/vec3.hpp \
		3rdParty/glm/glm/detail/type_vec3.hpp \
		3rdParty/glm/glm/detail/type_vec.hpp \
		3rdParty/glm/glm/detail/precision.hpp \
		3rdParty/glm/glm/detail/setup.hpp \
		3rdParty/glm/glm/simd/platform.h \
		3rdParty/glm/glm/detail/type_int.hpp \
		3rdParty/glm/glm/detail/_swizzle.hpp \
		3rdParty/glm/glm/detail/_swizzle_func.hpp \
		3rdParty/glm/glm/detail/type_vec3.inl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		3rdParty/glm/glm/glm.hpp \
		3rdParty/glm/glm/detail/_fixes.hpp \
		3rdParty/glm/glm/fwd.hpp \
		3rdParty/glm/glm/detail/type_float.hpp \
		3rdParty/glm/glm/detail/type_mat.hpp \
		3rdParty/glm/glm/vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.hpp \
		3rdParty/glm/glm/detail/type_vec2.inl \
		3rdParty/glm/glm/vec4.hpp \
		3rdParty/glm/glm/detail/type_vec4.hpp \
		3rdParty/glm/glm/detail/type_vec4.inl \
		3rdParty/glm/glm/detail/type_vec4_simd.inl \
		3rdParty/glm/glm/mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.hpp \
		3rdParty/glm/glm/detail/type_mat2x2.inl \
		3rdParty/glm/glm/detail/func_matrix.hpp \
		3rdParty/glm/glm/mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.hpp \
		3rdParty/glm/glm/detail/type_mat2x3.inl \
		3rdParty/glm/glm/mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.hpp \
		3rdParty/glm/glm/detail/type_mat2x4.inl \
		3rdParty/glm/glm/mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.hpp \
		3rdParty/glm/glm/detail/type_mat3x2.inl \
		3rdParty/glm/glm/mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.hpp \
		3rdParty/glm/glm/detail/type_mat3x3.inl \
		3rdParty/glm/glm/mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.hpp \
		3rdParty/glm/glm/detail/type_mat3x4.inl \
		3rdParty/glm/glm/mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.hpp \
		3rdParty/glm/glm/detail/type_mat4x2.inl \
		3rdParty/glm/glm/mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.hpp \
		3rdParty/glm/glm/detail/type_mat4x3.inl \
		3rdParty/glm/glm/mat4x4.hpp \
		3rdParty/glm/glm/detail/type_mat4x4.hpp \
		3rdParty/glm/glm/detail/type_mat4x4.inl \
		3rdParty/glm/glm/detail/type_mat4x4_simd.inl \
		3rdParty/glm/glm/detail/func_matrix.inl \
		3rdParty/glm/glm/geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.hpp \
		3rdParty/glm/glm/detail/func_geometric.inl \
		3rdParty/glm/glm/detail/func_exponential.hpp \
		3rdParty/glm/glm/detail/type_vec1.hpp \
		3rdParty/glm/glm/detail/type_vec1.inl \
		3rdParty/glm/glm/detail/func_exponential.inl \
		3rdParty/glm/glm/detail/func_vector_relational.hpp \
		3rdParty/glm/glm/detail/func_vector_relational.inl \
		3rdParty/glm/glm/detail/func_vector_relational_simd.inl \
		3rdParty/glm/glm/detail/_vectorize.hpp \
		3rdParty/glm/glm/detail/func_exponential_simd.inl \
		3rdParty/glm/glm/simd/exponential.h \
		3rdParty/glm/glm/detail/func_common.hpp \
		3rdParty/glm/glm/detail/func_common.inl \
		3rdParty/glm/glm/detail/func_common_simd.inl \
		3rdParty/glm/glm/simd/common.h \
		3rdParty/glm/glm/detail/func_geometric_simd.inl \
		3rdParty/glm/glm/simd/geometric.h \
		3rdParty/glm/glm/detail/func_matrix_simd.inl \
		3rdParty/glm/glm/simd/matrix.h \
		3rdParty/glm/glm/trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.hpp \
		3rdParty/glm/glm/detail/func_trigonometric.inl \
		3rdParty/glm/glm/detail/func_trigonometric_simd.inl \
		3rdParty/glm/glm/exponential.hpp \
		3rdParty/glm/glm/common.hpp \
		3rdParty/glm/glm/packing.hpp \
		3rdParty/glm/glm/detail/func_packing.hpp \
		3rdParty/glm/glm/detail/func_packing.inl \
		3rdParty/glm/glm/detail/type_half.hpp \
		3rdParty/glm/glm/detail/type_half.inl \
		3rdParty/glm/glm/detail/func_packing_simd.inl \
		3rdParty/glm/glm/matrix.hpp \
		3rdParty/glm/glm/vector_relational.hpp \
		3rdParty/glm/glm/integer.hpp \
		3rdParty/glm/glm/detail/func_integer.hpp \
		3rdParty/glm/glm/detail/func_integer.inl \
		3rdParty/glm/glm/detail/func_integer_simd.inl \
		3rdParty/glm/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o heightmap.o heightmap.cpp

qrc_3dvisualization.o: qrc_3dvisualization.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_3dvisualization.o qrc_3dvisualization.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qrangeslider.o: moc_qrangeslider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qrangeslider.o moc_qrangeslider.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

